-- jiangcuo-middle.json — 225 題
-- type: jiangcuo, difficulty: middle
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"莫名其妙","wrong":"莫明其妙","explanation":"「莫名其妙」的「名」指說出、形容,意為「無法用言語形容其中奧妙」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"再接再厲","wrong":"再接再勵","explanation":"「厲」原指磨利,「再接再厲」典出鬥雞,出戰前再次磨利雞嘴。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"川流不息","wrong":"穿流不息","explanation":"「川」即河流,形容人潮、車輛像河水一樣連續不斷。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"變本加厲","wrong":"變本加利","explanation":"「厲」為猛烈、加劇之意;非「利益」之「利」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"重蹈覆轍","wrong":"重蹈復轍","explanation":"「覆」音 ㄈㄨˋ,翻覆;比喻再次走上失敗的舊路。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"不脛而走","wrong":"不徑而走","explanation":"「脛」音 ㄐㄧㄥˋ,小腿;意指消息沒有腿卻能傳遍各地。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"一籌莫展","wrong":"一愁莫展","explanation":"「籌」為計策、籌劃;指一點計策也施展不出,與「發愁」無關。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"心無旁騖","wrong":"心無旁鶩","explanation":"「騖」音 ㄨˋ,奔馳、追求;「鶩」是野鴨,二字常被混用。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"趨之若鶩","wrong":"趨之若騖","explanation":"「鶩」音 ㄨˋ,野鴨;指人群像鴨子般成群追逐而去。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"真知灼見","wrong":"真知卓見","explanation":"「灼」音 ㄓㄨㄛˊ,明白透徹;指真正而透徹的見解。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"委曲求全","wrong":"委屈求全","explanation":"「委曲」指曲意遷就;「委屈」是受冤屈,意思不同。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"出類拔萃","wrong":"出類拔粹","explanation":"「萃」音 ㄘㄨㄟˋ,原指草叢生,引申為聚集、出眾。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"相形見絀","wrong":"相形見拙","explanation":"「絀」音 ㄔㄨˋ,意為不足;比較之下顯得不夠好。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"嶄露頭角","wrong":"展露頭角","explanation":"「嶄」音 ㄓㄢˇ,高聳突出;指才能初次顯現。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"美輪美奐","wrong":"美侖美奐","explanation":"「輪」指高大;「奐」指眾多。原形容房屋高大華麗。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"鴉雀無聲","wrong":"鴉鵲無聲","explanation":"「雀」指麻雀;「鵲」是喜鵲。原句以連烏鴉麻雀都不出聲形容極為安靜。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"黃粱一夢","wrong":"黃梁一夢","explanation":"「粱」音 ㄌㄧㄤˊ,小米;典出煮黃粱飯時做的大夢,比喻虛幻。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"一筆勾銷","wrong":"一筆勾消","explanation":"「銷」有取消、抹去之意;舊帳一筆全部勾掉。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"走投無路","wrong":"走頭無路","explanation":"「投」為投奔、投靠;意指無處可去,並非「頭」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"暗箭難防","wrong":"暗劍難防","explanation":"「箭」可從暗處射出;「劍」需近身搏鬥,不適用此意。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"罄竹難書","wrong":"磬竹難書","explanation":"「罄」音 ㄑㄧㄥˋ,用盡;指竹簡用盡也寫不完,多形容罪狀繁多。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"一塌糊塗","wrong":"一蹋糊塗","explanation":"「塌」為倒塌、崩壞;「蹋」是踩踏,意思不同。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"文質彬彬","wrong":"文質斌斌","explanation":"「彬彬」形容文雅有禮,是固定寫法;「斌」是異體字。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"不假思索","wrong":"不加思索","explanation":"「假」音 ㄐㄧㄚˇ,意為借助、憑藉;不必借助思考即能反應。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"揭竿而起","wrong":"揭桿而起","explanation":"「竿」為竹竿;秦末百姓舉竹竿作旗起義,故用「竿」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"鞠躬盡瘁","wrong":"鞠躬盡萃","explanation":"「瘁」音 ㄘㄨㄟˋ,勞累、勞苦;竭盡心力直至病累。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"一鼓作氣","wrong":"一股作氣","explanation":"「鼓」為擊鼓;古代作戰擊鼓振奮士氣,第一次擊鼓最為有力。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"矯枉過正","wrong":"嬌枉過正","explanation":"「矯」音 ㄐㄧㄠˇ,意為糾正;糾正過了頭反而失之偏頗。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"滄海桑田","wrong":"蒼海桑田","explanation":"「滄」指水深青色;大海變為桑田,比喻世事變遷。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"妨礙","wrong":"防礙","explanation":"「妨」音 ㄈㄤˊ,阻擋、有害於;「防」為防備之意,用法不同。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"即使","wrong":"既使","explanation":"「即使」表示假設、退一步的語氣;「既」表示已經,與此處語意不合。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"披星戴月","wrong":"披星帶月","explanation":"「戴」是頭頂著;星辰加月色覆於頭上,形容夜以繼日的辛勞。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"破釜沉舟","wrong":"破斧沉舟","explanation":"「釜」是鍋,項羽渡河打破炊鍋、沉船,自絕退路。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"披荊斬棘","wrong":"披荊斬刺","explanation":"「棘」音 ㄐㄧˊ,多刺植物;比喻克服重重困難。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"刻苦銘心","wrong":"刻骨銘心","explanation":"正確為「刻骨銘心」,刻在骨上、銘記於心。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"刻骨銘心","wrong":"刻骨明心","explanation":"「銘」是鐫刻、深記;非「明」(明白)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"耳濡目染","wrong":"耳孺目染","explanation":"「濡」音 ㄖㄨˊ,沾濕、薰陶;非「孺」(小孩)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"嘔心瀝血","wrong":"歐心瀝血","explanation":"「嘔」音 ㄡˇ,吐出;比喻費盡心血。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"五體投地","wrong":"五體頭地","explanation":"「投」是投擲、伏拜;形容極為佩服。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"光彩奪目","wrong":"光採奪目","explanation":"「彩」指色彩;非「採」(採集)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"再厲","wrong":"再勵","explanation":"動詞磨利之意用「厲」(同「礪」)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"按部就班","wrong":"按步就班","explanation":"「部」指部署、安排;非「步」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"開門見山","wrong":"開門見三","explanation":"「山」指山,一打開門就見到山,比喻直截了當。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"明察秋毫","wrong":"明察秋豪","explanation":"「毫」指細毛;非「豪」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"秋毫無犯","wrong":"秋豪無犯","explanation":"「毫」是細毛;紀律嚴明連細微之物都不侵犯。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"草菅人命","wrong":"草管人命","explanation":"「菅」音 ㄐㄧㄢ,茅草;視人命如草芥。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"嬌生慣養","wrong":"嬌生官養","explanation":"「慣」是習慣;形容嬌養過度。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"良莠不齊","wrong":"良芋不齊","explanation":"「莠」音 ㄧㄡˇ,雜草;良和雜混在一起,品質不齊。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"鋌而走險","wrong":"挺而走險","explanation":"「鋌」音 ㄊㄧㄥˇ,快走貌;在無路可走時冒險行事。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"既往不咎","wrong":"既往不究","explanation":"「咎」音 ㄐㄧㄡˋ,責難;對以往的過失不再追究。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"歸咎於","wrong":"歸究於","explanation":"「咎」是責備、歸罪;非「究」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"頭昏腦脹","wrong":"頭昏腦漲","explanation":"「脹」是腫脹、發脹;非「漲」(漲水、漲價)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"水漲船高","wrong":"水脹船高","explanation":"「漲」音 ㄓㄤˇ,水位升高;非「脹」(腫脹)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"姍姍來遲","wrong":"珊珊來遲","explanation":"「姍姍」形容走得緩慢;「珊」是珊瑚。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"陷阱","wrong":"陷井","explanation":"「阱」指深坑;「井」是水井,不同字。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"九霄雲外","wrong":"九宵雲外","explanation":"「霄」是天空;「宵」是夜晚。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"通宵達旦","wrong":"通霄達旦","explanation":"「宵」是夜晚;指整夜直到天亮。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"墨守成規","wrong":"默守成規","explanation":"「墨」典自墨翟善守城,堅守不變;非「默」(沉默)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"沉默寡言","wrong":"沉墨寡言","explanation":"「默」是沉默;非「墨」(墨水)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"涇渭分明","wrong":"徑渭分明","explanation":"「涇」、「渭」皆為河名,二河相匯仍清濁分明。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"百無聊賴","wrong":"百無聊奈","explanation":"「賴」音 ㄌㄞˋ,依靠;非「奈」(無奈)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"無可奈何","wrong":"無可耐何","explanation":"「奈」是奈何、怎麼樣;非「耐」(忍耐)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"事必躬親","wrong":"事必恭親","explanation":"「躬」是親自;「恭」是恭敬,語意不同。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"門可羅雀","wrong":"門可羅鵲","explanation":"「雀」指鳥雀;「鵲」是喜鵲,固定詞用「雀」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"歡呼雀躍","wrong":"歡呼鵲躍","explanation":"「雀」泛指鳥雀;非「鵲」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"歡欣鼓舞","wrong":"歡心鼓舞","explanation":"「欣」是喜悅;「心」非此意。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"歡天喜地","wrong":"歡天喜的","explanation":"「地」用於副詞 (歡天喜地);非「的」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"曇花一現","wrong":"談花一現","explanation":"「曇」音 ㄊㄢˊ,曇花夜開即謝,比喻美好事物短暫。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"鋒芒畢露","wrong":"鋒芒必露","explanation":"「畢」是全、完全;非「必」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"原原本本","wrong":"源源本本","explanation":"「原原」指追根究柢;「源」是水源。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"源遠流長","wrong":"原遠流長","explanation":"「源」指源頭;「原」是原本。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"五彩繽紛","wrong":"五采繽紛","explanation":"「彩」是色彩;「采」是采摘 (古字)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"前赴後繼","wrong":"前撲後繼","explanation":"「赴」是前往;「撲」是撲倒。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"前仆後繼","wrong":"前赴後繼","explanation":"「仆」音 ㄆㄨ,跌倒;前者倒下後者繼起,形容奮不顧身。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"嗤之以鼻","wrong":"癡之以鼻","explanation":"「嗤」是譏笑;「癡」是癡迷。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"叱吒風雲","wrong":"叱咤風雲","explanation":"教育部標準用「吒」(音 ㄓㄚˋ);兩字常被誤用。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"如雷貫耳","wrong":"如雷灌耳","explanation":"「貫」是穿過;「灌」是灌注。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"一氣呵成","wrong":"一氣喝成","explanation":"「呵」是吹氣;「喝」是飲。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"五花八門","wrong":"五化八門","explanation":"「花」指花樣;「化」是變化。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"杞人憂天","wrong":"杞人優天","explanation":"「憂」是憂慮;「優」是優秀。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"養尊處優","wrong":"養尊處憂","explanation":"「優」是優渥;「憂」是憂慮。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"輕而易舉","wrong":"輕而易居","explanation":"「舉」是舉起;「居」是居住。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"含辛茹苦","wrong":"含心茹苦","explanation":"「辛」是辛苦;「心」是心臟。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"飲鴆止渴","wrong":"飲鳩止渴","explanation":"「鴆」音 ㄓㄣˋ,毒鳥;「鳩」是鳩鳥,不同字。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"無所事事","wrong":"無所是是","explanation":"「事事」是各種事務;非「是是」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"煞費苦心","wrong":"殺費苦心","explanation":"「煞」是極、甚;「殺」是殺害。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"凶神惡煞","wrong":"凶神惡殺","explanation":"「煞」指凶神;此處非「殺」字。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"層出不窮","wrong":"曾出不窮","explanation":"「層」是層次;「曾」是曾經。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"曾經滄海","wrong":"層經滄海","explanation":"「曾」是曾經;「層」是層次。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"故步自封","wrong":"固步自封","explanation":"「故」指舊有;「故步」即舊有步法,沿用此意。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"瞭如指掌","wrong":"了如指掌","explanation":"「瞭」音 ㄌㄧㄠˇ,清楚明白;教育部正字用「瞭」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"恍如隔世","wrong":"恍若隔世","explanation":"「如」與「若」皆通,但成語固定為「恍如」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"流連忘返","wrong":"留連忘返","explanation":"教育部標準用「流連」;「留連」是異體寫法。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"明日黃花","wrong":"昨日黃花","explanation":"典出蘇軾詩,「明日」即重陽過後;比喻過時之事。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"差強人意","wrong":"差強人事","explanation":"「人意」指人之心意;「人事」是錯誤寫法。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"汗流浹背","wrong":"汗流夾背","explanation":"「浹」音 ㄐㄧㄚˊ,溼透;非「夾」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"風塵僕僕","wrong":"風塵僕仆","explanation":"疊字應用「僕僕」表示奔忙;非「仆」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"如火如荼","wrong":"如火如塗","explanation":"「荼」音 ㄊㄨˊ,茅草開白花;比喻氣勢盛大。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"鳥語花香","wrong":"鳥羽花香","explanation":"「語」指鳥鳴;非「羽」(羽毛)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"卓爾不群","wrong":"卓爾不君","explanation":"「群」指眾人;特立獨行不同凡俗。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"高瞻遠矚","wrong":"高瞻遠囑","explanation":"「矚」音 ㄓㄨˇ,注視;非「囑」(囑咐)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"囑咐","wrong":"矚咐","explanation":"「囑」是囑咐;「矚」是注視。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"鋒利","wrong":"鋒厲","explanation":"指刀刃用「利」;「厲」是猛烈、磨利。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"屈指可數","wrong":"曲指可數","explanation":"「屈」是彎曲手指;「曲」音 ㄑㄩ。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"忐忑不安","wrong":"忑忐不安","explanation":"「忐」音 ㄊㄢˇ,上下顛倒之心,形容不安。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"惶惶不可終日","wrong":"皇皇不可終日","explanation":"「惶」是恐懼;「皇」是君王、堂皇。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"堂而皇之","wrong":"堂而惶之","explanation":"「皇」指堂皇;「惶」是恐懼。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"鳩占鵲巢","wrong":"鳩佔鵲巢","explanation":"教育部標準用「占」;指強占他人之物。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"覬覦","wrong":"覤覦","explanation":"「覬覦」音 ㄐㄧˋ ㄩˊ,非分之想。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"洶湧","wrong":"匈湧","explanation":"「洶」加水部;非「匈」(匈奴)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"窈窕","wrong":"窕窈","explanation":"順序為「窈窕」(音 ㄧㄠˇ ㄊㄧㄠˇ)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"絡繹不絕","wrong":"駱繹不絕","explanation":"「絡」是聯絡、絡繹;「駱」是駱駝。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"駱駝","wrong":"絡駝","explanation":"「駱」是駱駝;「絡」是脈絡。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"風靡一時","wrong":"風糜一時","explanation":"「靡」音 ㄇㄧˇ,倒下、傾倒;非「糜」(粥)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"奢靡","wrong":"奢糜","explanation":"「靡」是浪費;「糜」是粥、爛掉。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"披露","wrong":"批露","explanation":"「披」是打開、揭示;「批」是批評。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"批評","wrong":"披評","explanation":"「批」是批評;「披」是揭露。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"頻繁","wrong":"瀕繁","explanation":"「頻」是頻率;「瀕」是接近、瀕臨。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"瀕臨","wrong":"頻臨","explanation":"「瀕」是接近;「頻」是頻率。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"嬌縱","wrong":"嬌綜","explanation":"「縱」是放縱;「綜」是綜合。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"綜合","wrong":"縱合","explanation":"「綜」是綜合;「縱」是放縱。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"輻射","wrong":"福射","explanation":"「輻」音 ㄈㄨˊ,車輪輻條;非「福」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"福利","wrong":"輻利","explanation":"「福」是福氣;「輻」是輻射。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"幅員","wrong":"福員","explanation":"「幅」音 ㄈㄨˊ,寬度;國土範圍稱幅員。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"震撼","wrong":"震憾","explanation":"「撼」是搖動 (提手);非「憾」(遺憾,豎心)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"遺憾","wrong":"遺撼","explanation":"「憾」是遺憾 (豎心);「撼」是搖動。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"潛意識","wrong":"淺意識","explanation":"「潛」是潛伏 (深處);「淺」是浮淺。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"淺顯","wrong":"潛顯","explanation":"「淺」是淺白;「潛」是潛伏。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"頒佈","wrong":"頒怖","explanation":"「佈」是發佈;「怖」是恐怖。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"恐怖","wrong":"恐佈","explanation":"「怖」是恐懼 (豎心);「佈」是發佈。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"翱翔","wrong":"敖翔","explanation":"「翱」音 ㄠˊ,翅膀張開;非「敖」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"傲慢","wrong":"敖慢","explanation":"「傲」是傲慢 (人字旁);「敖」是遊蕩。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"璀璨","wrong":"催燦","explanation":"「璀璨」音 ㄘㄨㄟˇ ㄘㄢˋ,玉光燦爛。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"惆悵","wrong":"愁悵","explanation":"「惆」音 ㄔㄡˊ,失意;「愁」是憂愁。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"駕馭","wrong":"駕御","explanation":"「馭」音 ㄩˋ,駕車;教育部標準用「駕馭」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"提綱挈領","wrong":"提綱契領","explanation":"「挈」音 ㄑㄧㄝˋ,提起;非「契」(契約)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"契機","wrong":"挈機","explanation":"「契」是契合、契機;「挈」是提起。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"鞭辟入裡","wrong":"鞭闢入裡","explanation":"「辟」(音 ㄆㄧˋ) 是透徹;「闢」是開闢。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"開闢","wrong":"開辟","explanation":"「闢」音 ㄆㄧˋ,開拓;與「辟」古字相通,現代多用「闢」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"砥礪","wrong":"低厲","explanation":"「砥礪」是磨練;「砥」音 ㄉㄧˇ。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"瑕疵","wrong":"暇疵","explanation":"「瑕」是玉的斑點;「暇」是空閒。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"閒暇","wrong":"閒瑕","explanation":"「暇」是空閒;「瑕」是玉斑。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"濫竽充數","wrong":"濫芋充數","explanation":"「竽」是樂器;南郭先生不會吹竽混在樂團中。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"芋頭","wrong":"竽頭","explanation":"「芋」是芋頭;「竽」是樂器。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"摩肩接踵","wrong":"摩肩接腫","explanation":"「踵」音 ㄓㄨㄥˇ,腳跟;形容人多擁擠。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"腫脹","wrong":"踵脹","explanation":"「腫」是腫起;「踵」是腳跟。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"循循善誘","wrong":"巡巡善誘","explanation":"「循循」是有次序地;非「巡」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"巡邏","wrong":"循邏","explanation":"「巡」是巡視;「循」是依循。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"枯燥","wrong":"枯躁","explanation":"「燥」是乾燥 (火部);「躁」是急躁。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"急躁","wrong":"急燥","explanation":"「躁」是性急 (足部);「燥」是乾燥。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"搗蛋","wrong":"擣蛋","explanation":"教育部標準寫「搗」,音 ㄉㄠˇ。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"舶來品","wrong":"泊來品","explanation":"「舶」是大船;經船運來的進口貨。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"湖泊","wrong":"湖舶","explanation":"「泊」音 ㄆㄛ,湖泊;「舶」是船。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"惺惺相惜","wrong":"猩猩相惜","explanation":"「惺惺」指聰明人;非「猩猩」(動物)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"逆來順受","wrong":"逆來順授","explanation":"「受」是接受;「授」是給予。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"沿襲","wrong":"沿習","explanation":"「襲」是沿用、襲承;非「習」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"陳腔濫調","wrong":"陳腔爛調","explanation":"「濫」是過多、不切實;非「爛」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"風花雪月","wrong":"風花雪夜","explanation":"四項自然景物的並列,固定用「月」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"鬼鬼祟祟","wrong":"鬼鬼崇崇","explanation":"「祟」音 ㄙㄨㄟˋ,作怪;「崇」是崇高。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"崇高","wrong":"祟高","explanation":"「崇」是高大、崇敬;「祟」是作祟。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"惡貫滿盈","wrong":"惡冠滿盈","explanation":"「貫」是穿錢的繩子;惡事多如繩串穿錢。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"冠冕堂皇","wrong":"觀冕堂皇","explanation":"「冠」音 ㄍㄨㄢ,帽子;「冠冕」喻體面。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"如願以償","wrong":"如願以嘗","explanation":"「償」是補償、實現;「嘗」是品嘗。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"品嘗","wrong":"品償","explanation":"「嘗」是品嘗;「償」是賠償。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"飛揚跋扈","wrong":"飛揚拔扈","explanation":"「跋」音 ㄅㄚˊ,專橫;非「拔」(拔起)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"題跋","wrong":"題拔","explanation":"「跋」是書文後序;「拔」是拔取。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"無與倫比","wrong":"無與論比","explanation":"「倫」是同類;「論」是議論。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"討論","wrong":"討倫","explanation":"「論」是討論;「倫」是同類。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"鋃鐺入獄","wrong":"狼鐺入獄","explanation":"「鋃鐺」音 ㄌㄤˊ ㄉㄤ,鎖鏈聲。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"狼狽為奸","wrong":"郎狽為奸","explanation":"「狼」與「狽」皆為動物,合作為惡。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"杯弓蛇影","wrong":"杯供蛇影","explanation":"「弓」指弓影投映;非「供」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"風和日麗","wrong":"風和日厲","explanation":"「麗」是明媚;「厲」是猛烈。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"嬌豔欲滴","wrong":"嬌艷欲低","explanation":"「滴」指像水滴下;非「低」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"水落石出","wrong":"水落實出","explanation":"水退後石頭露出,比喻真相大白。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"瞋目結舌","wrong":"嗔目結舌","explanation":"「瞋」音 ㄔㄣ,睜大眼睛;教育部標準用「瞋」(目部)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"嗔怒","wrong":"瞋怒","explanation":"指生氣多用「嗔」(口部);兩字相關但部首不同。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"震耳欲聾","wrong":"振耳欲聾","explanation":"「震」是震動;「振」是振奮。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"振奮","wrong":"震奮","explanation":"「振」是振奮、振作;「震」是震動。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"水泄不通","wrong":"水洩不通","explanation":"教育部標準用「水泄不通」(雙水形容)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"洩漏","wrong":"泄漏","explanation":"「洩漏」教育部用「洩」;與「泄不通」之「泄」不同字義。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"鬱鬱寡歡","wrong":"郁郁寡歡","explanation":"「鬱」是憂愁;「郁」是芬芳。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"濃郁","wrong":"濃鬱","explanation":"「郁」是芳香;「鬱」是憂愁。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"虎視眈眈","wrong":"虎視耽耽","explanation":"「眈眈」目部,注視;「耽」是沉溺。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"耽誤","wrong":"眈誤","explanation":"「耽」是耽誤;「眈」是注視。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"如鯁在喉","wrong":"如梗在喉","explanation":"「鯁」音 ㄍㄥˇ,魚刺;非「梗」(植物枝梗)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"莖梗","wrong":"莖鯁","explanation":"「梗」是植物;「鯁」是魚刺。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"焚膏繼晷","wrong":"焚膏繼咎","explanation":"「晷」音 ㄍㄨㄟˇ,日影;繼日光以燈火照明。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"歸咎","wrong":"歸晷","explanation":"「咎」是責難;「晷」是日影。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"擱淺","wrong":"閣淺","explanation":"「擱」是放置;「閣」是樓閣。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"樓閣","wrong":"樓擱","explanation":"「閣」是樓閣;「擱」是放置。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"提攜","wrong":"提協","explanation":"「攜」是提帶、扶持;「協」是協助。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"協助","wrong":"攜助","explanation":"「協」是協助;「攜」是攜帶。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"翔實","wrong":"詳實","explanation":"教育部正字為「翔實」(翔有完備之意);現代亦接受「詳實」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"詳細","wrong":"翔細","explanation":"「詳」是詳細;「翔」是飛翔。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"洶湧澎湃","wrong":"洶涌彭湃","explanation":"「湧」是水冒出;教育部正字。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"恪守","wrong":"格守","explanation":"「恪」音 ㄎㄜˋ,恭敬謹慎;「格」是格子。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"瞻仰","wrong":"贍仰","explanation":"「瞻」是望、仰望;「贍」是贍養。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"贍養","wrong":"瞻養","explanation":"「贍」是供養;「瞻」是仰視。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"匱乏","wrong":"潰乏","explanation":"「匱」是缺乏;「潰」是潰散。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"崩潰","wrong":"崩匱","explanation":"「潰」是崩潰;「匱」是缺乏。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"奠基","wrong":"墊基","explanation":"「奠」是奠定;「墊」是墊高。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"墊腳","wrong":"奠腳","explanation":"「墊」是墊高;「奠」是奠定。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"鞭策","wrong":"鞭冊","explanation":"「策」是策略、馬鞭;「冊」是書冊。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"書冊","wrong":"書策","explanation":"「冊」是書冊;「策」是策略。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"耀眼","wrong":"曜眼","explanation":"「耀」是閃耀;「曜」古指日月星辰。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"絢爛","wrong":"洵爛","explanation":"「絢」是絢麗;「洵」是真實。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"頹廢","wrong":"頹費","explanation":"「廢」是廢棄;「費」是花費。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"浪費","wrong":"浪廢","explanation":"「費」是花費;「廢」是廢棄。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"裨益","wrong":"卑益","explanation":"「裨」音 ㄅㄧˋ,補助、有益;非「卑」(卑微)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"卑微","wrong":"裨微","explanation":"「卑」是卑微;「裨」是裨益。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"昂貴","wrong":"昂跪","explanation":"「貴」是貴重;「跪」是下跪。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"跪拜","wrong":"貴拜","explanation":"「跪」是下跪;「貴」是貴重。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"鍥而不舍","wrong":"契而不舍","explanation":"「鍥」音 ㄑㄧㄝˋ,雕刻;比喻持續努力。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"風馳電掣","wrong":"風馳電撤","explanation":"「掣」音 ㄔㄜˋ,牽引;形容極快。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"撤退","wrong":"掣退","explanation":"「撤」是撤離;「掣」是牽引。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"鴻鵠之志","wrong":"鴻浩之志","explanation":"「鵠」音 ㄏㄨˊ,大雁;比喻遠大志向。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"浩瀚","wrong":"鵠瀚","explanation":"「浩」是廣大;「鵠」是大雁。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"踟躕不前","wrong":"踟蹰不前","explanation":"教育部標準用「踟躕」(音 ㄔˊ ㄔㄨˊ)。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"佝僂","wrong":"勾僂","explanation":"「佝」音 ㄍㄡ,駝背;非「勾」。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"驟然","wrong":"聚然","explanation":"「驟」是急、忽然;「聚」是聚集。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"聚集","wrong":"驟集","explanation":"「聚」是聚集;「驟」是急。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"嗜好","wrong":"喧好","explanation":"「嗜」音 ㄕˋ,愛好;「喧」是喧嘩。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"喧嘩","wrong":"嗜嘩","explanation":"「喧」是喧鬧;「嗜」是嗜好。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"駕輕就熟","wrong":"駕輕就熱","explanation":"「熟」是熟悉;「熱」是熱度。"}');
INSERT INTO questions (type, difficulty, payload) VALUES ('jiangcuo', 'middle', '{"correct":"熟悉","wrong":"熱悉","explanation":"「熟」是熟悉;「熱」是熱度。"}');
